apiVersion: v1
kind: Pod
metadata:
  name: httpbin-pod
  labels:
    app: httpbin
spec:
  initContainers:
  # - name: init-networking
  #   image: us-central1-docker.pkg.dev/black-scope-358204/zerok-collector/init
  #   securityContext:
  #     capabilities:
  #       add:
  #       - NET_ADMIN
  #     privileged: true
  - image: soarinferret/iptablesproxy
    imagePullPolicy: IfNotPresent
    name: zerok-init
    command: [ 'sh', '-c', 'iptables -t nat -I PREROUTING 1 -p tcp -i eth0 --dport 80 -j REDIRECT --to-port 8000; echo updated iptables; iptables -t nat --list && sleep 5']
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
      privileged: true
  containers:
  - name: service
    image: kennethreitz/httpbin
    ports:
    - containerPort: 80
  - name: proxy
    image: us-central1-docker.pkg.dev/black-scope-358204/zerok-collector/proxy
    ports:
    - containerPort: 8000