apiVersion: v1
data:
  default.conf: |
    server {
        listen       80;
        server_name  localhost;
        access_log  /var/log/nginx/access.log  main;
        location / {
            add_header Content-Type text/plain;
            return 200 'target (listener)';
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
kind: ConfigMap
metadata:
  name: target-listener
  namespace: default
