apiVersion: v1
kind: Service
metadata:
  name: listener
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: target
    owner: zerok
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
