apiVersion: v1
data:
  default.conf: "server {\n  listen       80;\n  server_name  localhost;\n  access_log
    \ /var/log/nginx/access.log  main;\n  location / {\n    default_type text/html;\n
    \   # return 200 \"completed\";\n\n    proxy_http_version 1.1;\n    proxy_ssl_server_name
    on;\n    proxy_read_timeout 5m; \n    proxy_pass https://jsonplaceholder.typicode.com/todos/1;\n
    \   # proxy_pass https://dummyjson.com/products/1;\n  }\n  error_page   500 502
    503 504  /50x.html;\n  location = /50x.html {\n    root   /usr/share/nginx/html;\n
    \ }\n}\n"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"default.conf":"server {\n  listen       80;\n  server_name  localhost;\n  access_log  /var/log/nginx/access.log  main;\n  location / {\n    default_type text/html;\n    # return 200 \"completed\";\n\n    proxy_http_version 1.1;\n    proxy_ssl_server_name on;\n    proxy_read_timeout 5m; \n    proxy_pass https://jsonplaceholder.typicode.com/todos/1;\n    # proxy_pass https://dummyjson.com/products/1;\n  }\n  error_page   500 502 503 504  /50x.html;\n  location = /50x.html {\n    root   /usr/share/nginx/html;\n  }\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"target","namespace":"default"}}
  creationTimestamp: "2022-09-23T05:00:28Z"
  name: target
  namespace: default
  resourceVersion: "167022"
  uid: 3fb7eb24-b142-4b28-a0e7-f4f9b56ac98b
